#Containers' name can't contain _ (underscore) because scrapy is not able to handle it.
version: '2'

services:
  web-interface:
    build: web
    restart: always
    ports:
      - "8000:5000"
    volumes:
      - ./etc:/opt/torscraper/etc:ro
      - ./scripts:/opt/torscraper/scripts:ro
      - ./lib:/opt/torscraper/lib:ro
    depends_on:
      - db
      - elasticsearch
    container_name: "freshonions-torscraper-web-interface"

  db:
    build: db
    # uncomment if you want database to persist
    volumes:
      - db-data:/var/lib/mysql
    container_name: "freshonions-torscraper-db"


  crawler:
    build: .
    restart: always
    depends_on:
      - db
      - elasticsearch
    container_name: "freshonions-torscraper-crawler"

  elasticsearch:
    #image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    image: elasticsearch:5.6.10
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    container_name: "freshonions-torscraper-elasticsearch"

  kibana:
    #image: docker.elastic.co/kibana/kibana-oss:6.3.0
    image: kibana:5.6.10
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://freshonions-torscraper-elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    container_name: "freshonions-torscraper-kibana"

  tor-privoxy:
    restart: always
    build: tor-privoxy
    ports:
      - "9050:9050" # Tor proxy
      - "3129:8118" # Privoxy
    container_name: "freshonions-torscraper-tor-privoxy"

  tor-privoxy2:
    restart: always
    build: tor-privoxy2
    ports:
      - "9051:9051" # Tor proxy
      - "3130:8119" # Privoxy
    container_name: "freshonions-torscraper-tor-privoxy2"

  tor-privoxy3:
    restart: always
    build: tor-privoxy3
    ports:
      - "9052:9052" # Tor proxy
      - "3131:8120" # Privoxy
    container_name: "freshonions-torscraper-tor-privoxy3"

  tor-privoxy4:
    restart: always
    build: tor-privoxy4
    ports:
      - "9053:9053" # Tor proxy
      - "3132:8121" # Privoxy
    container_name: "freshonions-torscraper-tor-privoxy4"

volumes:
  es-data:
    driver: local
  db-data:
    driver: local
